name: peerdart
version: 0.5.4
homepage: https://github.com/MuhammedKpln/peerdart
description: Simple peer-to-peer with WebRTC for Dart. PeerJS port for Flutter.
repository: https://github.com/MuhammedKpln/peerdart
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.22.0'
dependencies:
  http: ^1.2.2
  uuid: ^4.4.2
  flutter_webrtc: 0.9.48+hotfix.1
  web_socket_channel: ^3.0.1
  events_emitter: ^0.5.2
dev_dependencies:
  lints: ^4.0.0
  flutter_test:
    sdk: flutter
